export const BARANGAYS = [
  "Anapog-Sibucao",
  "Argao",
  "Balanacan",
  "Banto",
  "Bintakay",
  "Bocboc",
  "Butansapa",
  "Candahon",
  "Capayang",
  "Danao",
  "Dulong Bayan",
  "Gitnang Bayan",
  "Guisian",
  "Hinadharan",
  "Hinanggayon",
  "Ino",
  "Janagdong",
  "Lamesa",
  "Laon",
  "Magapua",
  "Malayak",
  "Malusak",
  "Mampaitan",
  "Mangyan-Mababad",
  "Market Site",
  "Mataas na Bayan",
  "Mendez",
  "Nangka I",
  "Nangka II",
  "Paye",
  "Pili",
  "Puting Buhangin",
  "Sayao",
  "Silangan",
  "Sumangga",
  "Tarug",
  "Villa Mendez",
] as const;

export type BarangayName = typeof BARANGAYS[number];